from pathlib import Path
from typing import Iterable, List

from ase import Atoms

from .config import ELEMENT_ORDER


def ordered_elements(symbols: Iterable[str], element_order: List[str]) -> List[str]:
    present = set(symbols)
    ordered = [elem for elem in element_order if elem in present]
    extras = sorted(elem for elem in present if elem not in ordered)
    return ordered + extras


def _validate_wrapped(atoms: Atoms, tol: float = 1e-8) -> None:
    scaled = atoms.get_scaled_positions(wrap=False)
    minv = scaled.min()
    maxv = scaled.max()
    if minv < -tol or maxv > 1.0 + tol:
        raise ValueError(
            f"Wrapped coordinates out of bounds: scaled min={minv:.6e}, max={maxv:.6e}"
        )


def atoms_to_poscar(
    atoms: Atoms,
    poscar_path: Path,
    element_order: List[str] = None,
    comment: str = "Generated by nnpgen",
) -> None:
    if element_order is None:
        element_order = ELEMENT_ORDER

    if atoms.cell is None or atoms.cell.rank < 3:
        raise ValueError("Input structure does not contain a valid 3D cell for POSCAR output")

    wrapped = atoms.copy()
    wrapped.wrap()
    _validate_wrapped(wrapped)

    symbols = wrapped.get_chemical_symbols()
    elems = ordered_elements(symbols, element_order)
    if not elems:
        raise ValueError("No elements found in structure")

    grouped_indices = []
    counts = []
    for elem in elems:
        idx = [i for i, s in enumerate(symbols) if s == elem]
        grouped_indices.extend(idx)
        counts.append(len(idx))

    scaled = wrapped.get_scaled_positions(wrap=False)
    cell = wrapped.cell.array

    with poscar_path.open("w", encoding="utf-8") as f:
        f.write(f"{comment}\n")
        f.write("1.0\n")
        for vec in cell:
            f.write(f"{vec[0]:.16f} {vec[1]:.16f} {vec[2]:.16f}\n")
        f.write(" ".join(elems) + "\n")
        f.write(" ".join(str(c) for c in counts) + "\n")
        f.write("Direct\n")
        for i in grouped_indices:
            x, y, z = scaled[i]
            f.write(f"{x:.16f} {y:.16f} {z:.16f}\n")
